version: "2.1"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  zipkin:
    image: openzipkin/zipkin:2.18
    ports:
      - 9411:9411