= R2DBC issue reproducer

This project is used to reproduce issue https://github.com/r2dbc/r2dbc-proxy/issues/94

== Run

    docker-compose up -d
    mvn clean spring-boot:run

on another terminal you can run

    curl http://localhost:8080/test-without-binding

You can see on logs something like that:

    2021-06-07 13:50:20.687  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.v.i.d.p.Repository             : before executing query mono
    2021-06-07 13:50:20.689 DEBUG 10130 --- [actor-tcp-nio-1] o.s.d.r2dbc.core.DefaultDatabaseClient   : Executing SQL statement [select pg_sleep(3), '1' as data;]
    2021-06-07 13:50:20.691 DEBUG 10130 --- [actor-tcp-nio-1] o.s.d.r2dbc.core.NamedParameterExpander  : Expanding SQL statement [select pg_sleep(3), '1' as data;] to [select pg_sleep(3), '1' as data;]
    2021-06-07 13:50:20.696  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingLifeCycleListener   : beforeExecuteQuery > start the query select pg_sleep(3), '1' as data;
    2021-06-07 13:50:20.697  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener beforeQuery > start the query select pg_sleep(3), '1' as data;
    2021-06-07 13:50:23.702  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener eachQueryResult > a result on the query select pg_sleep(3), '1' as data; 0
    2021-06-07 13:50:23.703  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingLifeCycleListener   : afterExecuteQuery > end the query select pg_sleep(3), '1' as data;
    2021-06-07 13:50:23.703  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener afterQuery > end the query select pg_sleep(3), '1' as data; 3007ms execInfo.isSuccess = true

We can see that `afterQuery` is called after the `eachQueryResult`. And the time between `beforeQuery` and `afterQuery` is > 3s.

Now you can run:

on another terminal you can run

    curl http://localhost:8080/test-with-binding

You can see on logs something like that:

    2021-06-07 13:52:47.314  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.v.i.d.p.Repository             : before executing query mono
    2021-06-07 13:52:47.314 DEBUG 10130 --- [actor-tcp-nio-1] o.s.d.r2dbc.core.DefaultDatabaseClient   : Executing SQL statement [select pg_sleep(:duration), '1' as data]
    2021-06-07 13:52:47.321 DEBUG 10130 --- [actor-tcp-nio-1] o.s.d.r2dbc.core.NamedParameterExpander  : Expanding SQL statement [select pg_sleep(:duration), '1' as data] to [select pg_sleep($1), '1' as data]
    2021-06-07 13:52:47.328  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingLifeCycleListener   : beforeExecuteQuery > start the query select pg_sleep($1), '1' as data
    2021-06-07 13:52:47.328  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener beforeQuery > start the query select pg_sleep($1), '1' as data
    2021-06-07 13:52:47.336  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingLifeCycleListener   : afterExecuteQuery > end the query select pg_sleep($1), '1' as data
    2021-06-07 13:52:47.337  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener afterQuery > end the query select pg_sleep($1), '1' as data 8ms execInfo.isSuccess = true
    2021-06-07 13:52:50.339  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.c.d.TracingExecutionListener   : TracingExecutionListener eachQueryResult > a result on the query select pg_sleep($1), '1' as data 8
    2021-06-07 13:52:50.339  INFO 10130 --- [actor-tcp-nio-1] c.a.s.c.p.v.i.d.p.Repository             : after execute the query mono

On this log we can see that `afterQuery` is called before `eachQueryResult`. And the time between `afterQuery` and `beforeQuery` is < 20ms. And the time between `eachQueryResult` and `beforeQuery` is > 3s.

The difference between the two endpoint is that the first don't use var binding, and the second do.
