spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      initialSize: 10
      maxSize: 10
    properties:
      schema: public
    username: postgres
    password: mysecretpassword
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        data:
          r2dbc: TRACE
    io:
      r2dbc:
        postgresql:
          QUERY: TRACE
