spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  r2dbc:
    username: postgres
    password: mysecretpassword
    url: r2dbc:postgresql://localhost:5432


logging.level.io.r2dbc.postgresql.QUERY: "INFO"
logging.level.org.springframework.data.r2dbc: "DEBUG"
